#!/usr/bin/with-contenv bash
source /venv/bin/activate

# Configuration Directory *WITH* trailing slash
CONF_DIR=/root/.config/
CONFIGURED=false
while [ "${CONFIGURED}" == "false" ]; do

  while read -r line; do
    echo "Processing: $line"
    if [ "$line" != *"token"* ]; then
      echo "Good... At least you're not set to defaults!"
      TOKEN=$(cat ${CONF_DIR}/linode-cli | grep token | awk '{print $3}')
      if [ ${#TOKEN} == 64 ]; then
        echo "Apparently valid token"
        TOKEN=valid
      fi
    fi
  done < <(cat "${CONF_DIR}/linode-cli" | grep "token")
  
  if [ "${TOKEN}" == "valid" ]; then
    export CONFIGURED=true
    echo "Valid Configuration.  Launching linode-dyndns."
    linode-dyndns
  else
    echo "Your configuration appears invalid."
    echo "Run the following command to setup linode-cli :"
    echo "  docker compose exec linode-cli configure"
  fi
  sleep 1m
done
